telegram:
    token: [telegram token]
    chat: [channel id]
host1:
    port: 22
    username: host1_username
    password: host1_pass


host2: 
    port: 22
    username: host2_username
    password: host2_pass

ping:
    GRXCBJ01:
      jump_host: host1
      vrf: vrf_name
      ip:  host2
      prompt: prompt_name
      ip_list:
        - router1: 10.0.0.1
        - router2: 10.0.0.2

